E - Library

<img src = "https://drive.google.com/uc?id=15J_RDF7Dp2_yR07uu7iTZwIvTUkuW1Jf">

In [ ]:
# Instalasi library Faker
!pip install Faker
!pip install tabulate

Requirement already satisfied: Faker in /usr/local/lib/python3.10/dist-packages (25.0.1)
Requirement already satisfied: python-dateutil>=2.4 in /usr/local/lib/python3.10/dist-packages (from Faker) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.4->Faker) (1.16.0)
Requirement already satisfied: tabulate in /usr/local/lib/python3.10/dist-packages (0.9.0)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# Import Library yang akan digunakan
from faker import Faker
from tabulate import tabulate
import random
from datetime import datetime, timedelta
import csv
import pandas as pd
import re

In [ ]:
# Definisikan bahwa data yang digunakan menggunakan format Indonesia
fake = Faker('id_ID')

## Membuat dummy data

### Dummy data yang dibuat adalah tabel-tabel berikut:

* libraries
* users
* publishers
* authors
* categories
* books
* book at library
* loan
* hold

In [ ]:
books_metadata = pd.read_csv("/content/drive/MyDrive/Pacmann/Dataset/books.csv", encoding='latin-1', on_bad_lines='skip', sep=';')
books_metadata.head()

<ipython-input-59-e6cbb87743af>:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books_metadata = pd.read_csv("/content/drive/MyDrive/Pacmann/Dataset/books.csv", encoding='latin-1', on_bad_lines='skip', sep=';')

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [ ]:
books_metadata['Book-Title'].nunique()

242135

In [ ]:
def generate_libraries_data(num, lib_name):
    """
    Generate data for libraries.

    Args:
        num (int): Number of rows of data to generate.
        lib_name (list): List of library names.

    Returns:
        pandas.DataFrame: A DataFrame containing library data with columns:
            - library_id (int): Unique identifier for each library.
            - library_name (str): Name of the library.
            - email (str): Email address of the library (generated based on library name).
            - contact_number (str): Contact phone number of the library (generated).
    """
    library_names = lib_name
    email = [f"{library_name.replace(' ', '_')}@umail.com" for library_name in library_names]

    library = {"library_id": [i+1 for i in range(num)],
               "library_name": [i for i in library_names],
               "email": [i for i in email],
               "contact_number": []}

    for i in range(num):
      phone_number = fake.phone_number()
      library['contact_number'].append(phone_number)

    df = pd.DataFrame(library)
    return df

library_names = ["Perpustakaan Universitas Raharja", "Grahatama Pustaka", "Pustakalana", "Library Satu University", "Perpustakaan Universitas Tama"]
df_library = pd.DataFrame(generate_libraries_data(num=5, lib_name=library_names))
df_library

,library_id,library_name,email,contact_number
0,1,Perpustakaan Universitas Raharja,Perpustakaan_Universitas_Raharja@umail.com,(0077) 553 3998
1,2,Grahatama Pustaka,Grahatama_Pustaka@umail.com,+62 (985) 884 8792
2,3,Pustakalana,Pustakalana@umail.com,+62 (85) 511 8320
3,4,Library Satu University,Library_Satu_University@umail.com,+62-0950-488-4279
4,5,Perpustakaan Universitas Tama,Perpustakaan_Universitas_Tama@umail.com,0895508604

In [ ]:
def generate_users_data(num=5):
    """
    Generate user data.

    Args:
        num (int, optional): Number of user records to generate. Defaults to 5.

    Returns:
        pandas.DataFrame: DataFrame containing user data with columns:
            - user_id (int): Unique identifier for each user.
            - username (str): Username generated based on first name, last name, and phone number.
            - first_name (str): User's first name.
            - last_name (str): User's last name.
            - email (str): User's email address.
            - password (str): User's password.
            - contact_number (str): User's contact phone number.
    """

    first_name_list = []
    last_name_list = []
    phone_number_list = []
    password_list = []
    username_list = []
    email_list = []

    for i in range(num):
      first_name = fake.first_name()
      last_name = fake.last_name()
      phone_number = fake.phone_number()
      password = fake.password()
      username = f"{first_name.lower()}_{last_name.lower()}{phone_number[-2:-1]}"
      email = f"{first_name.lower()}.{last_name.lower()}@usermail.com"

      first_name_list.append(first_name)
      last_name_list.append(last_name)
      phone_number_list.append(phone_number)
      password_list.append(password)
      username_list.append(username)
      email_list.append(email)

    users = {"user_id": [i+1 for i in range(num)],
              "username": username_list,
              "first_name": first_name_list,
              "last_name": last_name_list,
              "email": email_list,
              "password": password_list,
              "contact_number": phone_number_list
             }

    df = pd.DataFrame(users)
    return df

df_users = pd.DataFrame(generate_users_data(num=20))
df_users.head()

,user_id,username,first_name,last_name,email,password,contact_number
0,1,ade_ramadan3,Ade,Ramadan,ade.ramadan@usermail.com,*j4SUh1DV#,+62 (005) 727 4130
1,2,hardi_simbolon6,Hardi,Simbolon,hardi.simbolon@usermail.com,6_1pYt(Y9c,+62-85-592-4869
2,3,olivia_nainggolan3,Olivia,Nainggolan,olivia.nainggolan@usermail.com,(bajJSUg#4,087 050 3837
3,4,ivan_januar7,Ivan,Januar,ivan.januar@usermail.com,n3P^ZPGe#6,(091) 043-4271
4,5,zahra_nuraini3,Zahra,Nuraini,zahra.nuraini@usermail.com,@7R23G16dU,+62 (004) 019-3438

In [ ]:
def generate_authors_data(num, books_metadata):
    """
    Generate author data.

    Args:
        num (int): Number of author records to generate.
        books_metadata (pandas.DataFrame): DataFrame containing book metadata.

    Returns:
        pandas.DataFrame: DataFrame containing author data with columns:
            - author_id (int): Unique identifier for each author.
            - name (str): Author's name.
            - email (str): Author's email address (generated based on name).
            - contact_number (str): Author's contact phone number (generated).

    """
    author_name_list = books_metadata['Book-Author'].unique().tolist()
    email_list = [f"{name}.{str(index+12)}@authormail.com" for index, name in enumerate(author_name_list)]
    email_list = [email.split(' ')[-1] for email in email_list]
    phone_number_list = []

    for i in range(num):
      phone_number = fake.phone_number()
      phone_number_list.append(phone_number)


    author = {"author_id": [i+1 for i in range(num)],
               "name": author_name_list[:num],
               "email": email_list[:num],
               "contact_number": phone_number_list}

    df = pd.DataFrame(author)
    return df

df_authors = pd.DataFrame(generate_authors_data(100, books_metadata))
df_authors.head()

,author_id,name,email,contact_number
0,1,Mark P. O. Morford,Morford.12@authormail.com,(088) 668-6491
1,2,Richard Bruce Wright,Wright.13@authormail.com,(055) 935-4854
2,3,Carlo D'Este,D'Este.14@authormail.com,+62 (29) 172 9350
3,4,Gina Bari Kolata,Kolata.15@authormail.com,+62 (013) 794-0890
4,5,E. J. W. Barber,Barber.16@authormail.com,(063) 609 3295

In [ ]:
def generate_publishers_data(num, books_metadata):
    """
    Generate publisher data.

    Args:
        num (int): Number of publisher records to generate.
        books_metadata (pandas.DataFrame): DataFrame containing book metadata.

    Returns:
        pandas.DataFrame: DataFrame containing publisher data with columns:
            - publisher_id (int): Unique identifier for each publisher.
            - name (str): Publisher's name.
            - address (str): Publisher's address.
            - email (str): Publisher's email address (generated based on name).
            - contact_number (str): Publisher's contact phone number (generated).

    """

    publisher_name_list = books_metadata['Publisher'].unique().tolist()
    address_list = []
    email_list = [f"{name}.{str(index+12)}@publishermail.com" for index, name in enumerate(publisher_name_list)]
    email_list = [email.split(' ')[-1] for email in email_list]
    phone_number_list = []

    for i in range(num):
      phone_number = fake.phone_number()
      address = fake.address()
      phone_number_list.append(phone_number)
      address_list.append(address)

    author = {"publisher_id": [i+1 for i in range(num)],
               "name": publisher_name_list[:num],
               "address": address_list,
               "email": email_list[:num],
               "contact_number": phone_number_list}

    df = pd.DataFrame(author)
    return df

df_publishers = pd.DataFrame(generate_publishers_data(70, books_metadata))
df_publishers.head()

,publisher_id,name,address,email,contact_number
0,1,Oxford University Press,"Gg. Cikutra Barat No. 0\nSawahlunto, Maluku Ut...",Press.12@publishermail.com,+62-0468-588-2551
1,2,HarperFlamingo Canada,"Gg. Moch. Toha No. 3\nBogor, ST 41608",Canada.13@publishermail.com,087 150 7614
2,3,HarperPerennial,"Jalan Gegerkalong Hilir No. 117\nBekasi, Nusa ...",HarperPerennial.14@publishermail.com,+62 (069) 303 7472
3,4,Farrar Straus Giroux,"Gg. Laswi No. 6\nSamarinda, SG 09772",Giroux.15@publishermail.com,(0857) 352 2994
4,5,W. W. Norton &amp; Company,"Gang H.J Maemunah No. 1\nPayakumbuh, BA 18550",Company.16@publishermail.com,+62 (99) 633 7528

In [ ]:
def generate_categories_data(num, cat_name):
    """
    Generate category data.

    Args:
        num (int): Number of category records to generate.
        cat_name (list): List of category names.

    Returns:
        pandas.DataFrame: DataFrame containing category data with columns:
            - category_id (int): Unique identifier for each category.
            - category_name (str): Name of the category.

    """
    category_name = cat_name
    category = {"category_id": [i+1 for i in range(num)],
               "category_name": [i for i in category_name]}

    df = pd.DataFrame(category)
    return df

category_name = ["Mystery", "Thriller", "Science Fiction", "Fantasy", "Romance", "Non-Fiction", "Biography"]
df_categories = pd.DataFrame(generate_categories_data(num=7, cat_name=category_name))
df_categories

   category_id    category_name
0            1          Mystery
1            2         Thriller
2            3  Science Fiction
3            4          Fantasy
4            5          Romance
5            6      Non-Fiction
6            7        Biography

In [ ]:
def generate_books_data(num, books_metadata, df_categories, df_authors, df_publishers):
    """
    Generate book data.

    Args:
        num (int): Number of book records to generate.
        books_metadata (pandas.DataFrame): DataFrame containing book metadata.
        df_categories (pandas.DataFrame): DataFrame containing category data.
        df_authors (pandas.DataFrame): DataFrame containing author data.
        df_publishers (pandas.DataFrame): DataFrame containing publisher data.

    Returns:
        pandas.DataFrame: DataFrame containing book data with columns:
            - book_id (int): Unique identifier for each book.
            - book_title (str): Title of the book (cleaned from non-alphanumeric characters).
            - date_of_publication (datetime.date): Date of publication of the book.
            - category_id (int): ID of the category the book belongs to.
            - author_id (int): ID of the author of the book.
            - publisher_id (int): ID of the publisher of the book.

    """

    def clean_string(input_string):
        # Remove non-alphanumeric characters
        cleaned_string = re.sub(r'[^a-zA-Z0-9\s]', '', input_string)
        return cleaned_string

    # Assuming you have a DataFrame books_metadata with a column 'Book-Title'
    book_title_list = books_metadata['Book-Title'].unique().tolist()

    # Clean the book titles using the clean_string function
    cleaned_titles = [clean_string(title) for title in book_title_list]

    date_of_pub_list = []
    category_id_list = []
    author_id_list = []
    publisher_id_list = []

    for i in range(num):
      date_of_pub = fake.date_time_between(start_date=datetime(2000, 1, 1), end_date=datetime(2023, 1, 1)).date()
      date_of_pub_list.append(date_of_pub)
      category_id_list.append(random.choice(df_categories['category_id']))
      author_id_list.append(random.choice(df_authors['author_id']))
      publisher_id_list.append(random.choice(df_publishers['publisher_id']))

    author = {"book_id": [i+1 for i in range(num)],
               "book_title": cleaned_titles[:num],
               "date_of_publication": date_of_pub_list,
               "category_id": category_id_list,
               "author_id": author_id_list,
               "publisher_id": publisher_id_list}

    df = pd.DataFrame(author)
    return df

df_books = pd.DataFrame(generate_books_data(1000, books_metadata, df_categories, df_authors, df_publishers))
df_books.head()

,book_id,book_title,date_of_publication,category_id,author_id,publisher_id
0,1,Classical Mythology,2011-09-13,2,98,65
1,2,Clara Callan,2012-11-26,6,94,19
2,3,Decision in Normandy,2014-04-06,1,43,59
3,4,Flu The Story of the Great Influenza Pandemic ...,2006-12-18,6,7,51
4,5,The Mummies of Urumchi,2020-11-06,7,53,9

In [ ]:
def generate_bookatlibrary_data(num, df_library):
    """
    Generate data for books available at libraries.

    Args:
        num (int): Number of book-at-library records to generate.
        df_library (pandas.DataFrame): DataFrame containing library data.

    Returns:
        pandas.DataFrame: DataFrame containing book-at-library data with columns:
            - library_book_id (int): Unique identifier for each library-book entry.
            - library_id (int): ID of the library where the book is available.
            - book_id (int): ID of the book available at the library.
            - quantity (int): Number of copies of the book available at the library.

    """

    book_at_library = {"library_book_id": [i+1 for i in range(num)],
                       "library_id": [random.choice(df_library['library_id']) for _ in range(num)],
                       "book_id": [i+1 for i in range(num)],
                       "quantity": [random.randint(1, 4) for _ in range(num)]}

    df = pd.DataFrame(book_at_library)
    return df

df_book_at_library = pd.DataFrame(generate_bookatlibrary_data(1000, df_library))
df_book_at_library = df_book_at_library.drop_duplicates(subset=['library_id', 'book_id'], keep='last')
df_book_at_library

     library_book_id  library_id  book_id  quantity
0                  1           3        1         2
1                  2           1        2         4
2                  3           2        3         2
3                  4           5        4         1
4                  5           4        5         2
..               ...         ...      ...       ...
995              996           2      996         1
996              997           4      997         4
997              998           4      998         3
998              999           5      999         1
999             1000           1     1000         4

[1000 rows x 4 columns]

In [ ]:
def generate_loan_data(num, df_users, df_book_at_library):
    """
    Generate data for loans.

    Args:
        num (int): Number of loan records to generate.
        df_users (pandas.DataFrame): DataFrame containing user data.
        df_book_at_library (pandas.DataFrame): DataFrame containing book-at-library data.

    Returns:
        pandas.DataFrame: DataFrame containing loan data with columns:
            - loan_id (int): Unique identifier for each loan.
            - user_id (int): ID of the user taking the loan.
            - library_book_id (int): ID of the book-at-library entry for the loan.
            - loan_date (datetime): Date when the loan was issued.
            - due_date (datetime): Date when the loan is due.
            - status (str): Status of the loan ('On Loan', 'Returned', 'Overdue').
            - return_date (datetime): Date when the book was returned, if applicable.

    """

    loan_date_list = []
    due_date_list = []
    return_date_list = []

    for i in range(num):
        loan_date = fake.date_time_between(start_date=datetime(2024, 1, 1), end_date=datetime.now())
        due_date = loan_date + timedelta(days=14)
        loan_date_list.append(loan_date)
        due_date_list.append(due_date)
        return_date_list.append(None)

    status_list = random.choices(['On Loan', 'Returned', 'Overdue'], weights=[0.3, 0.6, 0.2], k=num)
    for i, status in enumerate(status_list):
        if status == 'Returned':
             return_date_list[i] = loan_date_list[i] + timedelta(days=random.randint(1, 13))
        elif status == 'Overdue':
             return_date_list[i] = loan_date_list[i] + timedelta(days=random.randint(15, 20))
        elif status == 'On Loan':
             return_date_list[i] = None

    loan_data = {
        "loan_id": [i + 1 for i in range(num)],
        "user_id": [random.choice(df_users['user_id']) for _ in range(num)],
        "library_book_id": [random.choice(df_book_at_library['library_book_id']) for _ in range(num)],
        "loan_date": loan_date_list,
        "due_date": due_date_list,
        "status": status_list,
        "return_date": return_date_list,
    }

    df = pd.DataFrame(loan_data)
    return df


df_loan = pd.DataFrame(generate_loan_data(1500, df_users, df_book_at_library))
df_loan.head(30)

,loan_id,user_id,library_book_id,loan_date,due_date,status,return_date
0,1,2,423,2024-03-18 10:52:51.849940,2024-04-01 10:52:51.849940,Overdue,2024-04-04 10:52:51.849940
1,2,16,520,2024-05-06 21:41:39.886429,2024-05-20 21:41:39.886429,Returned,2024-05-14 21:41:39.886429
2,3,15,926,2024-05-07 13:11:29.470214,2024-05-21 13:11:29.470214,On Loan,NaT
3,4,5,912,2024-02-12 19:30:54.583794,2024-02-26 19:30:54.583794,Returned,2024-02-18 19:30:54.583794
4,5,5,847,2024-02-01 14:25:55.705536,2024-02-15 14:25:55.705536,Returned,2024-02-03 14:25:55.705536
5,6,8,838,2024-04-05 19:13:16.440872,2024-04-19 19:13:16.440872,Overdue,2024-04-20 19:13:16.440872
6,7,13,90,2024-01-20 13:12:22.150668,2024-02-03 13:12:22.150668,On Loan,NaT
7,8,3,30,2024-05-01 20:42:50.855809,2024-05-15 20:42:50.855809,Overdue,2024-05-19 20:42:50.855809
8,9,8,678,2024-02-01 09:31:54.937243,2024-02-15 09:31:54.937243,Returned,2024-02-03 09:31:54.937243
9,10,10,353,2024-04-30 16:30:38.670077,2024-05-14 16:30:38.670077,On Loan,NaT
10,11,1,490,2024-01-06 11:54:10.920379,2024-01-20 11:54:10.920379,Returned,2024-01-11 11:54:10.920379
11,12,12,156,2024-03-05 10:09:00.071633,2024-03-19 10:09:00.071633,Returned,2024-03-15 10:09:00.071633
12,13,11,699,2024-04-04 14:12:50.857827,2024-04-18 14:12:50.857827,Returned,2024-04-12 14:12:50.857827
13,14,4,202,2024-01-08 00:32:44.850287,2024-01-22 00:32:44.850287,Returned,2024-01-20 00:32:44.850287
14,15,6,978,2024-04-29 16:39:57.657614,2024-05-13 16:39:57.657614,Returned,2024-05-02 16:39:57.657614
15,16,14,287,2024-04-17 23:05:34.519305,2024-05-01 23:05:34.519305,Overdue,2024-05-05 23:05:34.519305
16,17,16,140,2024-03-07 15:10:09.599154,2024-03-21 15:10:09.599154,Returned,2024-03-14 15:10:09.599154
17,18,17,954,2024-02-14 11:53:18.916673,2024-02-28 11:53:18.916673,Returned,2024-02-23 11:53:18.916673
18,19,16,524,2024-03-22 04:39:48.550248,2024-04-05 04:39:48.550248,Returned,2024-04-02 04:39:48.550248
19,20,19,349,2024-05-02 10:59:30.509833,2024-05-16 10:59:30.509833,Returned,2024-05-11 10:59:30.509833
20,21,9,6,2024-02-03 10:06:20.203826,2024-02-17 10:06:20.203826,Returned,2024-02-10 10:06:20.203826
21,22,11,647,2024-02-02 09:39:13.278893,2024-02-16 09:39:13.278893,Returned,2024-02-05 09:39:13.278893
22,23,12,825,2024-03-20 06:00:57.535305,2024-04-03 06:00:57.535305,Overdue,2024-04-04 06:00:57.535305
23,24,17,972,2024-03-27 15:02:13.904609,2024-04-10 15:02:13.904609,Returned,2024-04-09 15:02:13.904609
24,25,12,538,2024-02-27 11:22:38.176306,2024-03-12 11:22:38.176306,Overdue,2024-03-18 11:22:38.176306
25,26,5,152,2024-02-04 01:49:02.580618,2024-02-18 01:49:02.580618,On Loan,NaT
26,27,14,739,2024-03-03 03:11:16.786263,2024-03-17 03:11:16.786263,Returned,2024-03-08 03:11:16.786263
27,28,18,169,2024-03-02 09:41:48.981386,2024-03-16 09:41:48.981386,Returned,2024-03-15 09:41:48.981386
28,29,18,229,2024-02-15 04:49:35.284770,2024-02-29 04:49:35.284770,Returned,2024-02-27 04:49:35.284770
29,30,11,870,2024-04-01 01:08:09.439626,2024-04-15 01:08:09.439626,Overdue,2024-04-19 01:08:09.439626

In [ ]:
def generate_hold_data(num, df_users, df_book_at_library):
    """
    Generate data for holds.

    Args:
        num (int): Number of hold records to generate.
        df_users (pandas.DataFrame): DataFrame containing user data.
        df_book_at_library (pandas.DataFrame): DataFrame containing book-at-library data.

    Returns:
        pandas.DataFrame: DataFrame containing hold data with columns:
            - hold_id (int): Unique identifier for each hold.
            - user_id (int): ID of the user placing the hold.
            - library_book_id (int): ID of the book-at-library entry for the hold.
            - hold_date (datetime): Date when the hold was placed.
            - expire_date (datetime): Date when the hold expires, or None if still active.
            - status (str): Status of the hold ('In Queue' or 'Expired').

    """
    hold_start_date_list = []
    hold_end_date_list = []
    expire_date_list = []
    status_list = []

    for i in range(num):
        hold_start_date = fake.date_time_between(start_date=datetime(2024, 4, 25), end_date=datetime.now())
        hold_start_date_list.append(hold_start_date)

        if hold_start_date >= datetime(2024, 5, 2) and hold_start_date < datetime.now():
          expire_date = None
        else:
          expire_date = hold_start_date + timedelta(days=7)
        expire_date_list.append(expire_date)

        if expire_date is None:
          status = 'In Queue'
        else:
          status = 'Expired'
        status_list.append(status)

    hold_data = {
        "hold_id": [i + 1 for i in range(num)],
        "user_id": [random.choice(df_users['user_id']) for _ in range(num)],
        "library_book_id": [random.choice(df_book_at_library['library_book_id']) for _ in range(num)],
        "hold_date": hold_start_date_list,
        "expire_date": expire_date_list,
        "status": status_list,
    }

    df = pd.DataFrame(hold_data)
    return df


df_hold = pd.DataFrame(generate_hold_data(600, df_users, df_book_at_library))
df_hold.head(30)

,hold_id,user_id,library_book_id,hold_date,expire_date,status
0,1,7,308,2024-04-29 19:43:13.838707,2024-05-06 19:43:13.838707,Expired
1,2,10,720,2024-05-08 07:03:22.165179,NaT,In Queue
2,3,15,696,2024-05-05 02:07:04.175099,NaT,In Queue
3,4,7,354,2024-05-07 04:09:09.471859,NaT,In Queue
4,5,1,936,2024-04-30 04:19:59.344388,2024-05-07 04:19:59.344388,Expired
5,6,5,432,2024-05-04 07:20:46.356001,NaT,In Queue
6,7,7,768,2024-05-05 19:43:22.676368,NaT,In Queue
7,8,17,201,2024-05-08 07:15:35.908776,NaT,In Queue
8,9,5,87,2024-05-02 04:34:09.390794,NaT,In Queue
9,10,16,29,2024-05-06 03:24:24.584457,NaT,In Queue
10,11,7,714,2024-04-26 17:15:55.108749,2024-05-03 17:15:55.108749,Expired
11,12,2,82,2024-04-28 07:16:38.820404,2024-05-05 07:16:38.820404,Expired
12,13,4,713,2024-05-06 04:11:38.269171,NaT,In Queue
13,14,18,686,2024-05-03 06:48:58.954283,NaT,In Queue
14,15,17,298,2024-05-06 18:01:31.181416,NaT,In Queue
15,16,1,834,2024-04-28 03:05:50.079534,2024-05-05 03:05:50.079534,Expired
16,17,5,622,2024-04-29 12:43:43.140104,2024-05-06 12:43:43.140104,Expired
17,18,6,728,2024-05-06 20:58:43.283626,NaT,In Queue
18,19,10,232,2024-05-01 01:47:59.343462,2024-05-08 01:47:59.343462,Expired
19,20,11,768,2024-05-07 18:09:14.873153,NaT,In Queue
20,21,17,143,2024-05-03 14:05:56.325513,NaT,In Queue
21,22,18,532,2024-04-28 09:44:38.407937,2024-05-05 09:44:38.407937,Expired
22,23,10,25,2024-04-28 00:14:42.337788,2024-05-05 00:14:42.337788,Expired
23,24,13,9,2024-04-25 15:51:21.946096,2024-05-02 15:51:21.946096,Expired
24,25,5,815,2024-04-30 04:05:44.811258,2024-05-07 04:05:44.811258,Expired
25,26,12,205,2024-04-25 03:49:36.222976,2024-05-02 03:49:36.222976,Expired
26,27,4,830,2024-05-07 21:49:41.535927,NaT,In Queue
27,28,1,590,2024-05-04 21:22:44.247485,NaT,In Queue
28,29,15,869,2024-05-02 07:50:28.553879,NaT,In Queue
29,30,5,958,2024-05-05 01:10:28.997307,NaT,In Queue

In [ ]:
# Save to CSV
df_library.to_csv('libraries.csv', index=False)
df_categories.to_csv('category.csv', index=False)
df_publishers.to_csv('publishers.csv', index=False)
df_authors.to_csv('authors.csv', index=False)
df_users.to_csv('users.csv', index=False)
df_books.to_csv('books.csv', index=False)
df_book_at_library.to_csv('library_books.csv', index=False)
df_loan.to_csv('loans.csv', index=False)
df_hold.to_csv('holds.csv', index=False)